### ISSUE TITLE
After crash, Factor UI won't startup

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2468] opened 2021-05-16 13:03 UTC
After crashing Factor #2467, rerunning Factor stops with an error
```
$ ./factor.com
Error in thread 23 (UI update, [ self ui-thread set-global update-ui-loop ]):

Win32 error 0xc00705aa: Unknown error 0xc00705aa
(U) Quotation: [ set-namestack init-catchstack self quot>> call => stop ]
(O) Word: update-ui-loop
(O) Word: update-ui
(O) Word: notify-queued
(O) Method: M\ world graft*
(O) Method: M\ windows-ui-backend (open-window)
(O) Word: setup-gl
(O) Word: get-rc
(O) Word: n>win32-error-check
(O) Word: throw-windows-error
(O) Word: windows-error
(O) Method: M\ object throw
(U) Quotation: [
        OBJ-CURRENT-THREAD special-object error-thread set-global
        current-continuation => error-continuation set-global
        [ original-error set-global ] [ rethrow ] bi
    ]
```

**Comment by nomennescio** [comment] 2021-05-16 13:08
Update: it seems this error is related to some other scarce system resource (not memory). Once I closed another application, I could succesfully start Factor.

HOWEVER, I would expect better error messaging. When running Factor.exe, it silently fails.

**Comment by erg** [comment] 2021-12-14 22:56
``Insufficient system resources``, maybe the actionable item here is showing the error if Factor.exe crashes?

**Comment by nomennescio** [comment] 2021-12-15 11:37
> `Insufficient system resources`, maybe the actionable item here is showing the error if Factor.exe crashes?

I'm not entirely sure what the 0xc00705aa error is. Google shows some references in the context of OpenGL, but indeed, "Insufficient system resources" seems mentioned multiple times.

**Comment by erg** [comment] 2021-12-29 03:05
Speculatively closing as dupe of https://github.com/factor/factor/issues/2254

**Closed by erg** 2021-12-29 03:05 UTC
Labels: errors, startup, memory-footprint
