### ISSUE TITLE
funny stack effects break homoiconicity

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#864] opened 2013-04-24 20:44 UTC
```factor
IN: scratchpad ( x: "a string" -- ) .
( x: a string -- )
```

Should quote strings.

**Comment by erg** [comment] 2016-03-31 06:17
``( a "b c d" -- e )`` parses to ``{ "a" "\"" "b" "c" "d\"" -- "e" }``. There are more problems than just fixing it like this:

``M: string effect>string dup [ blank? ] any? [ "\"" dup surround ] when ;``

Closing as not a bug for now.

**Closed by erg** 2016-03-31 06:17 UTC
Labels: help, parser, prettyprinter, stack-checker
