### ISSUE TITLE
Bitstreams <msb0-bit-writer> has no write method

### ISSUE THREAD

**Issue by hyphz** [factor/factor#1254] opened 2014-12-16 00:34 UTC
The Poke method - which is used for writing - is not implemented for msb0-bit-writer, so bitwriters of this type effectively do nothing.

**Comment by erg** [comment] 2022-01-07 19:56
Duplicate of newer bug https://github.com/factor/factor/issues/1254 with more discussion. closing this one

**Closed by erg** 2022-01-07 19:56 UTC
Labels: performance, library, io, data-structures, streams, bits
