### ISSUE TITLE
Upgrade reCaptcha on concatenative.org

### ISSUE THREAD

**Issue by akkartik** [factor/factor#2045] opened 2018-08-13 20:33 UTC
The version currently deployed is not supported anymore, and that seems to break all form submissions site-wide.

**Comment by bpollack** [comment] 2018-08-13 21:28
Thanks for the report @akkartik, but taht's a duplicate of #1991. I'm working on it and hope to have something tomorrow.

**Closed by bpollack** 2018-08-13 21:28 UTC
