### ISSUE TITLE
load-all crashes Factor.exe

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2467] opened 2021-05-16 12:37 UTC
Windows 7, x86_64, Factor snapshot 2021-05-15. When using `load-all`, at some point Factor just crashes. I've plenty of RAM left, so that's not the issue. Is there any post-mortem info floating around?

**Comment by nomennescio** [comment] 2021-05-16 15:58
Update: when running factor.com, Factor reports the following error:
```
$ ./factor.com
ImportError: No module named site
```

**Comment by nomennescio** [comment] 2021-05-16 16:17
Update: this also crashes when run from the UI Walker.

**Comment by nomennescio** [comment] 2021-05-17 10:29
Update: after removing `extra/python`, `load-all` completed succesfully. HOWEVER, Factor should not have crashed in the first place, and I would expect to at least have some kind of error message / logging.

**Comment by erg** [comment] 2021-12-14 22:59
Closing as duplicate of https://github.com/factor/factor/issues/2469

**Closed by erg** 2021-12-14 22:59 UTC
Labels: crash, windows, python
