### ISSUE TITLE
GitHub syntax highlighting

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1212] opened 2014-11-22 16:16 UTC
Looks like GitHub switched away from Pygments (which has great Factor syntax highlighting support) to using Linguist which uses TextMate bundles.

Our TextMate bundle has comparatively mediocre Factor syntax highlighting and should be improved!

(Filing this issue mostly to remind me that I want to work on this)

**Comment by catb0t** [comment] 2018-02-05 14:47
Factor's GitHub syntax highlighting seems decent now, is this still a problem?

**Comment by mrjbq7** [comment] 2018-02-05 15:47
Decent, but it needs to parse a few more constructs and valid Factor literals, especially now that we have some pretty good syntax test files.

**Comment by bjourne** [comment] 2018-02-05 19:13
Take a look at the file: https://github.com/factor/factor/blob/master/misc/fuel/strange-syntax.factor I wrote it to test FUEL:s syntax highlighting, but it can of course be used to test GitHub's too.

**Comment by erg** [comment] 2022-01-07 04:46
Duplicate of https://github.com/factor/factor/issues/1032

**Closed by erg** 2022-01-07 04:46 UTC
Labels: website, documentation, tools, syntax-highlighting, help-wanted
