### ISSUE TITLE
Help crashes Factor on OS X 10.11.4

### ISSUE THREAD

**Issue by nicholas-spies** [factor/factor#1619] opened 2016-04-24 18:16 UTC
Evoking Help, either from the Help Menu or from the interactive console, causes Factor to be terminated, effectively locking up. This applies to both the "stable" and "development" versions on line as of 24 Apr 2016.

**Comment by mrjbq7** [comment] 2016-04-24 18:40
That's weird. It is a known issue with 0.97 ("stable") where it pops up a gl-error.  

But it should be fixed on development version.  Are you sure you tested the right versions?

**Comment by mrjbq7** [comment] 2016-04-24 18:41
I use 10.11.4 on my laptop and have no issues.

**Comment by mrjbq7** [comment] 2016-04-24 18:44
@erg I am driving but maybe you can test the binary download works properly?  I can try it in a few hours otherwise.

**Comment by nicholas-spies** [comment] 2016-04-24 19:06
I downloaded both stable and development binaries, and got the same result after dragging the Factor folder from the opened dmg to the Applications folder. In both cases this is the message given:
<img width="394" alt="factor error alert" src="https://cloud.githubusercontent.com/assets/10050002/14769749/05015f5c-0a2e-11e6-9a2d-7d13928f6726.png">

**Comment by nicholas-spies** [comment] 2016-04-24 19:23
...then, after pressing OK, there is underneath an empty Alert with no content, with the title Error. After closing Error and the Browser (which is also empty), and entering 3 4 + , giving the response 7, pressing the Help button gives the same result, ERROR as pictured in previous post, empty window titled Error, empty window titled Browser, and active Listener window under the other three Alerts/Windows.

I have installed Factor before (a few years ago) without problem, and was able to play with it, finding it very Forth-like in many respects. 

The problem described has happened the same way with both versions (the Mac 64-bit versions) a couple of times. Perhaps there is something wrong with my iMac with 5K Retina display? The error message language "An error occurred with drawing the world T...." and further down "...gl-error-tuple..." and finally "...invalid framebuffer operation" makes the error seem to involve an interaction with the display...

**Comment by mrjbq7** [comment] 2016-04-24 19:30
I think you aren't testing the development version properly but am not sure why. Is this the 64-bit download? 

Can you try running it from the DMG window that opens?

**Comment by mrjbq7** [comment] 2016-04-24 19:32
(There is a small chance the binary is not updated properly and it would work if built from source),

I will test myself on a couple hours.

**Comment by erg** [comment] 2016-04-24 20:53
I've definitely seen your crash before, but I just tried it on the OSX 64bit download from today and there is no crash for me.

Maybe try deleting your Factor from applications and then drag it in again?

**Comment by nicholas-spies** [comment] 2016-04-25 17:50
The 24 Apr 2016 Mac OS X 64-bit build brings up Help without error; I must have downloaded a version or two before this. If you don't know what the problem was, do a diff between the most recent build and the previous couple of versions to see what might have caused the error.

**Comment by erg** [comment] 2016-04-25 19:16
We've been messing with that bug lately. Glad it works for you!

**Closed by erg** 2016-04-25 19:16 UTC
Labels: macosx, opengl, ui

**Comment by mrjbq7** [comment] 2016-04-25 19:29
We know exactly what the problem is, OSX 10.11 introduced a change that caused GL framebuffers that worked fine in earlier versions to return an unexpected error code that we (as you saw) handled by crashing.

Since last couple months it should be fixed in such a way that everything works although the underlying issue of proper initialization isn't quite finished being fixed. The error is logged to the console if you run the UI from a terminal you might notice. 

Thanks for the report! Glad it's working for you!
