### ISSUE TITLE
Windows x64 build on factorcode.org is 1.5 months old

### ISSUE THREAD

**Issue by alex-ilin** [factor/factor#2407] opened 2020-12-27 22:42 UTC
I'd like to get a fresh release, so I can rebase my local branch on the top of `master`. My normal workflow is to download the development build zip-file, then take factor.exe and factor.image from it, copy to my working folder, then do `refresh-all save`. After that I'm good for the next few months.

Unfortunately, the latest Win64 build is over a month old and when I try to `refresh-all` with the latest `master` branch contents it crashes trying to reload `kernel`. If I revert changes to the `kernel` vocab, then it fails this way:
![factor_RzmDeldLP9](https://user-images.githubusercontent.com/169039/103180990-091e2280-489c-11eb-9ef4-54709b5db052.png)
And when I select the "Use fry vocab", it shows the following:
![factor_QZMHXK3AqZ](https://user-images.githubusercontent.com/169039/103181004-38349400-489c-11eb-9810-313bd95de455.png)
As you can see, my 4K screen is not tall enough to know what the issue is. Pressing `Down` and `Enter`, I can get to the next error, which should not be possible if the latest `master` commit bootstraps correctly for anyone, but I may be wrong.
![factor_Px178Ssstp](https://user-images.githubusercontent.com/169039/103181026-8ea1d280-489c-11eb-8978-b1135d8ca1a9.png)

Is there a way to build the latest image file without rebuilding the VM from source? I don't think there were any useful VM changes since the latest version available on factorcode.org (November 16th), and I don't have any Cpp compilers installed.

**Comment by alex-ilin** [comment] 2020-12-28 00:15
OK, I'll make it a follow-up here, though may be it should be a new separate issue.
I have managed to build factor with VS2019. I got the new amd64 executable and the new image file from the `master` commit `0fccda1f`.
After building, I start `factor.exe`, and press F2. For some reason it starts reloading some vocabs, then crashes.
![factor_IAKOshejIM](https://user-images.githubusercontent.com/169039/103182170-a5025b00-48a9-11eb-8310-da5ef2b3353d.png)
I tried doing the same using the `factor.com` executable to catch any console output, but there was no output. It just closes without a trace.

Why does it want to reload something after creating the fresh image? I would expect it to contain all the same file versions that I have checked out during the build.

**Comment by mrjbq7** [comment] 2020-12-29 22:21
Something to do with making boot images on my M1 MacBook Pro, using an X86-64 factor running on Rosetta2. 

Somehow a couple of the core vocabs show us as needing to refresh on Windows. Need to investigate further.

**Comment by bpollack** [comment] 2020-12-30 15:56
I use Windows for basically everything, and have a server I can trivially make cut and upload bootstraps for us; you want me to go that route? Then the boot images will be made on Windows for Windows, which avoids this issue.

This is a duplicate of #2382 by the way, but I can't figure out how to merge GitHub issues, so I'm leaving both open.

**Comment by bpollack** [comment] 2020-12-30 15:56
The temporary fix BTW @alex-ilin is to just make your own bootstrap image. Vaguely annoying, but it only takes a minute.

**Comment by alex-ilin** [comment] 2020-12-30 17:20
@bpollack, thanks for the hint! I've searched the help system for "bootstrap" and figured out what needs to be done. I'll submit a PR with this `bootstrap.cmd` script so that it's always handy:
```
@echo off
factor -e="USING: bootstrap.image io.launcher kernel sequences ; my-arch-name dup make-image \"factor.com -i=boot.\" \".image\" surround run-process wait-for-process drop"
```

**Comment by mrjbq7** [comment] 2020-12-30 17:21
Why can’t you just run build.cmd? Doesn’t it have a self-update command like build.sh?

**Comment by mrjbq7** [comment] 2020-12-30 17:22
Also to make a bootstrap image for your arch is simply:

factor -run=bootstrap.image

**Comment by alex-ilin** [comment] 2020-12-30 17:41
@mrjbq7, `build.cmd` downloads a bootstrap image, which is stale at the moment, if I understand correctly. Hence the desire to update `kernel` after bootstrap.

`factor -run=bootstrap.image` only makes the bootstrap image, while the proposed script also uses it to build the full image.

**Comment by bpollack** [comment] 2020-12-30 17:45
@mrjbq7 to be clear: `bootstrap.cmd` is very minimalist compared to `bootstrap.sh`. I can make them closer if we want, albeit I'd be tempted to just port it to PowerShell in the process.

**Comment by jonenst** [comment] 2020-12-30 18:15
Can't you run Bash scripts natively on windows these days ? Maybe we can drop the build.cmd in favor of build.sh?

**Comment by erg** [comment] 2020-12-30 18:17
If you can run Factor at all, try running ``make-my-image`` and bootstrapping. It should work unless something is really broken.

**Comment by mrjbq7** [comment] 2020-12-30 18:20
factor -run=bootstrap.image
factor -i=boot.windows-x86.64.image

Simple enough

**Comment by bpollack** [comment] 2020-12-30 21:05
> Can't you run Bash scripts natively on windows these days ? Maybe we can drop the build.cmd in favor of build.sh?

Not in a way where it'd be a viable replacement, but bringing `build.cmd` up to par with `build.sh` wouldn't be that difficult, if for no other reason than `build.cmd` only needs to worry about Windows, not all *nix variants.

**Comment by mrjbq7** [comment] 2020-12-30 21:20
Having build.cmd update and self-update seems useful. 

Right now only update.

**Comment by erg** [comment] 2021-02-11 15:28
- Boot image bakes in the ``build`` number so you have to bootstrap from the latest boot image before uploading images
- Windows is fixed now

**Closed by erg** 2021-02-11 15:28 UTC
