### ISSUE TITLE
Revert some things back for 0.98

### ISSUE THREAD

**Issue by mrjbq7** [factor/factor#1915] opened 2018-01-22 22:29 UTC
``<FUNCTOR:`` and ``<CLASS:``.

``subseq-start`` back to ``start``?  Or maybe ``search`` and rename ``binary-search``...

Triple quoted strings?

What else should we think about making more compatible with 0.97?

**Comment by AlexIljin** [comment] 2018-01-22 22:43
I wanted the triple-quoted strings, and I still think they could be useful sometimes. Although, I must admit, very rarely.

Why do we want to revert some things? To make code that's still on v0.97 more easily upgradeable to v0.98?

Does such code exist?

**Comment by mrjbq7** [comment] 2018-01-22 22:45
Well, for a couple reasons:

1) Partly because some users that you don't hear from much seem to use release versions only, not nightly builds.

2) I wanted 0.98 to be the "last best" version before we start mucking around with cool new parsing techniques that give us some neat refactoring and modeling tools (like parsing code for all platforms on any platform, etc.)

3) Because some of the changes like removing triple quotes and rename ``<FUNCTOR:`` and ``<CLASS:`` were for the new parser but since it isn't done yet I don't want to lock those changes in right now.

**Comment by AlexIljin** [comment] 2018-01-22 23:22
I agree, and I'm also one of those who prefers to stick to the stable version, especially when I'm new to something, and double-especially when it's a huge wacky programming language. I wouldn't want to be on the bleeding edge of the latter when I'm not even sure about the basics.

So, yes, a new stable release is due, and if you think those features aren't ready because of the incomplete parser, then revert them.

One of the things I remember is `iota` -> `<iota>`. It's a little controversial*, and I got used to it, but if you want compatibility with v0.97, that's one of the things to remember.

*The controversy is about exposing the implementation details. To me `iota` was just a way to create a for-loop (much like a different syntax for the `times` word), not a "virtual sequence". Putting it in angle brackets exposes the implementation details and makes the word 1.5 times longer and more difficult to type. (Yes, ergonomics are something I pay attention to, even in programming language design.)

**Comment by bjourne** [comment] 2018-01-23 22:28
It looks like the build bots build cleanly now almost all the time which is pretty, pretty good! I wonder if there are  any vocabs they don't test that they did test before? If so, it would be good if those tests ran when you run `load-all test-all` yourself, but not when the build bots do it.

Also `find-library`. It should work with the new only-return-name-of-file behaviour.

**Comment by AlexIljin** [comment] 2018-01-23 22:40
@bjourne: then why is the latest Windows nightly build a week old?

**Comment by erg** [comment] 2018-01-23 22:48
The machine is in Linux right now. I would really like to move it to the cloud... (Same machine does win32/win64/linux32 in vmware)

**Comment by bjourne** [comment] 2018-01-24 12:53
@AlexIljin Something is flaky with the Mason dashboard. But according to the mails I get from the build bot, windows x86-64 built successfully only a few hours ago.

**Comment by AlexIljin** [comment] 2018-01-24 13:24
@bjourne: yep, I see it in the download folder. Thanks for the heads-up! I got a little irritated by F2 crashing Factor on the latest checkout when I used the binaries (.exe and .image) built on January 16th.

**Comment by mrjbq7** [comment] 2018-01-24 13:27
What kind of crash?

Was it when you were updating to latest binary and image but then refreshing with all your local changes?

**Comment by AlexIljin** [comment] 2018-01-24 13:52
This is easy to reproduce: extract from "factor-windows-x86-64-2018-01-16-17-12.zip" the factor.exe and factor.image into a folder with the latest master, start and press F2. It will start refreshing the vocabs, then vanish from the screen. The latest vocab I see reloading is "ui.render", then 2 or 3 flash by too quickly to read their names, immediately before the window disappears.

What's strange is that Windows doesn't offer to "find a solution" for this (which is a signal about an unhandled exception). If I run the factor.com from a console I don't see it dropping into the debugger or anything like that. It appears as if it's terminated normally, there is no output on the console.

**Comment by mrjbq7** [comment] 2018-01-24 14:59
If you try that from the command line and not the UI does it work? Might be an issue of refreshing UI vocabs with UI running? Losing track of window handles or something?

**Comment by mrjbq7** [comment] 2018-01-24 14:59
factor.com -run=listener

**Comment by AlexIljin** [comment] 2018-01-24 16:39
Interesting idea!
Running without the UI worked, it managed to complete `refresh-all`. Here are the vocabs loaded after `ui.render`:
```
Loading resource:basis/ui/render/render.factor
Loading resource:basis/ui/ui-docs.factor
Loading resource:basis/ui/backend/windows/windows.factor
Loading resource:basis/math/bitwise/bitwise-docs.factor
Loading resource:basis/ui/event-loop/event-loop.factor
Loading resource:basis/ui/event-loop/event-loop-docs.factor
Loading resource:basis/windows/kernel32/kernel32.factor
Loading resource:basis/windows/messages/messages.factor
Loading resource:core/vocabs/vocabs.factor
Loading resource:basis/windows/user32/user32.factor
Loading resource:basis/ui/tools/browser/browser.factor
Loading resource:basis/ui/gadgets/editors/editors-docs.factor
Loading resource:basis/ui/tools/listener/listener.factor
Loading resource:basis/ui/operations/operations-docs.factor
Loading resource:basis/windows/gdiplus/gdiplus.factor
Loading resource:basis/windows/shell32/shell32.factor
Loading resource:core/checksums/checksums-docs.factor
Loading resource:basis/cpu/x86/assembler/assembler-docs.factor
Loading resource:basis/cpu/x86/features/features-docs.factor
Loading resource:basis/ui/tools/tools-docs.factor
<end-of-list>
```
Some of those at the top used to bring the GUI down on refresh.

**Comment by AlexIljin** [comment] 2018-01-24 16:40
I think it was either the `ui.backend.windows` or the `ui.event-loop`.

**Comment by mrjbq7** [comment] 2018-01-24 16:47
Okay, good. Not great we crash on refresh, but good that it’s probably related to reloading vocabs without migrating their resources.

**Comment by erg** [comment] 2018-08-01 22:48
.98 got released! closing.....

**Closed by erg** 2018-08-01 22:48 UTC
Labels: bikeshed, old-school, release, rename, syntax
