### ISSUE TITLE
standard output and input in factor

### ISSUE THREAD

**Issue by MortezaRahmaniJRP** [factor/factor#2287] opened 2020-05-05 21:28 UTC
Hello, every one!
I need your help, Just Now Please!
how to get std out in factor?
thank you in advance

**Comment by mrjbq7** [comment] 2020-05-05 21:30
What are you trying to accomplish?

When you run a Factor program from the command-line, the ``input-stream`` and ``output-stream`` are bound to stdin and stdout.

**Comment by MortezaRahmaniJRP** [comment] 2020-05-05 21:32
give me a real script example please

**Comment by mrjbq7** [comment] 2020-05-05 21:33
For example, this reads a line from stdin and writes it to stdout.

```factor
#!/path/to/factor
USING: io ;
IN: echo

: echo ( -- )
    readln print ;

MAIN: echo
```

Then run it:

```
$ factor echo.factor
hello
hello
```

**Comment by MortezaRahmaniJRP** [comment] 2020-05-05 21:40
i am a windows guy and use it in my project but after executing, i can not get that as a standard output in my project, so i think factor's in\output-stream is not standard in\output

**Comment by mrjbq7** [comment] 2020-05-05 21:51
You need to run it using factor.com not factor.exe.

See #2175

**Comment by MortezaRahmaniJRP** [comment] 2020-05-05 21:56
yes please, but not to stdout

**Comment by mrjbq7** [comment] 2020-05-05 21:58
What does that mean?

**Comment by MortezaRahmaniJRP** [comment] 2020-05-05 21:59
factor.exe is IDE and i need CLI so use factor.com and not work!

**Comment by mrjbq7** [comment] 2020-05-05 22:24
It works for me...

```
C:\factor> type echo.factor
USING: io ;
IN: echo
: echo ( -- ) readln print ;
MAIN: echo

C:\factor> factor echo.factor
asdfjkl;
asdfjkl;

C:\factor>
```

What is it that's not working about it?

**Comment by MortezaRahmaniJRP** [comment] 2020-05-05 22:30
we need std.write or std.print or std.printf or something like that!
It doesn't work!

**Comment by MortezaRahmaniJRP** [comment] 2020-05-05 22:32
there is no return value

**Comment by AlexIljin** [comment] 2020-05-05 23:08
No, it works. There is a return value.

**Comment by mrjbq7** [comment] 2020-05-05 23:10
If you'd like to include a test case showing what's not working, I can help you.  But we might be having a communication problem.

I'm not sure what "doesn't work", since I showed an example where it reads stdin and writes stdout.

I'm not sure what you mean by std.write, std.print, std.printf.  In Factor those might be ``write``, ``print`` and ``printf``.

I'm not sure what you mean by there is no return value.  The ``echo`` word in the example above does not take any arguments, nor return anything.  But the script returns an exit code of success after running:

```
C:\factor> echo %errorlevel%
0
```

What version of Factor are you using?

**Comment by mrjbq7** [comment] 2020-05-05 23:11
I should add that stdout redirection works, so it's definitely working for me:

```
C:\factor> factor echo.factor > foo.txt
hello

C:|factor> type foo.txt
hello
```

**Comment by mrjbq7** [comment] 2020-05-05 23:12
Are you having trouble in a deployed binary?

**Comment by mrjbq7** [comment] 2020-05-05 23:20
It's possible in your code that you are changing the ``input-stream`` or ``output-stream``...?

For example, in this code ``readln`` reads from the default stream (which is stdin), but ``print`` writes to a file instead of ``stdout`` because it's inside a ``with-file-writer`` scope:

```factor
USING: io io.encodings.utf8 io.files ;
IN: echo
: echo ( -- )
    readln
    "foo2.txt" utf8 [ print ] with-file-writer ;
MAIN: echo
```

See it work:

```
C:\factor factor echo2.factor
hello foo

C:\factor type foo2.txt
hello foo
```

**Comment by MortezaRahmaniJRP** [comment] 2020-05-07 05:19
Sorry for being misunderstood, i mean using it in my own project (as i said), which is under .NET, just a simple System.Diagnostics.ProcessStartInfo and  redirecting StandardOutput, Not in CMD

**Comment by melted** [comment] 2020-05-07 09:36
This is working for me:

```
using System;
using System.Diagnostics;

namespace factor
{
    class Program
    {
        static void Main(string[] args)
        {
            ProcessStartInfo psi = new ProcessStartInfo();
            psi.RedirectStandardInput = true;
            psi.RedirectStandardOutput = true;
            psi.Arguments = "script.factor";
            psi.FileName = "D:/Niklas/src/factor/factor.com";
            var process = Process.Start(psi);
            process.StandardInput.WriteLine("test");
            var output = process.StandardOutput.ReadToEnd();
            System.Console.WriteLine(output);
        }
    }
}
```

Note the `factor.com`

**Comment by MortezaRahmaniJRP** [comment] 2020-05-07 17:55
yes please and thanks, but i use  "psi.CreateNoWindow=true;" and (in my opinion) because of not being real standard output of factor's output, it returns null val(just test it!).
Realy, I Don't want "psi.CreateNoWindow=false" because "psi.WindowStyle = ProcessWindowStyle.Hidden;" Not works!, and that's not what I want

**Comment by MortezaRahmaniJRP** [comment] 2020-05-07 20:12
It should be noted that I do not have this problem in Idiris & Lua & Haskell or Harbour and so on.

**Comment by mrjbq7** [comment] 2020-05-07 20:41
Can you share a test case showing it’s not working?

Everyone on this thread so far has demonstrated no problem exists.

**Comment by MortezaRahmaniJRP** [comment] 2020-05-07 20:44
it's a .Net project that mentioned above

**Comment by MortezaRahmaniJRP** [comment] 2020-05-07 20:54
Suppose this is the case:
string msg = "";
            System.Diagnostics.ProcessStartInfo psi = new System.Diagnostics.ProcessStartInfo();
            
            psi.UseShellExecute = false;
            psi.RedirectStandardOutput = true;
            psi.CreateNoWindow =true;
            //psi.WindowStyle = ProcessWindowStyle.Hidden;
            psi.FileName = @"C:\factor\factor.com";
            psi.Arguments = @"C:\Users\msi\Desktop\PPX\Examples\myFactor.factor";
            
            using (System.Diagnostics.Process p = System.Diagnostics.Process.Start(psi))
            {

               using (System.IO.StreamReader str = p.StandardOutput)
                {
                    
                    
                   msg = str.ReadToEnd();
                    
                }
            }
            System.Windows.Forms.MessageBox.Show(msg);

**Comment by MortezaRahmaniJRP** [comment] 2020-05-07 21:00
It should be noted again that I do not have this problem in Idiris & Lua & Haskell or Harbour and so on.

**Comment by MortezaRahmaniJRP** [comment] 2020-05-07 21:10
myfactor.factor :

USE: io
IN: hello-world
: hello ( -- ) "Hello world\nthis is\tFactor" print ;
MAIN: hello

**Comment by mrjbq7** [comment] 2020-05-16 16:15
It's unclear to me exactly how to reproduce the issue you are having, but I'll keep this bug report open to investigate further.

**Comment by AlexIljin** [comment] 2020-05-16 16:33
In Windows 10x64's default console cmd.exe the following code
`factor.com -e="USING: io math.parser ; 12 number>string write" >1.txt`
creates file 1.txt with text "12" in it and produces no output on the console.

The following code redirects the standard error output:
`factor.com -e="USING: io math.parser ; 12 number>string write" 2>1.txt`
This produces the "12" output on the console and creates the empty 1.txt file.

Since the standard console works as expected, IMHO, case closed.

**Comment by mrjbq7** [comment] 2020-05-16 16:34
@AlexIljin what do you think is going on with calling it in a .NET context?

**Comment by AlexIljin** [comment] 2020-05-16 17:20
I think that maybe `psi.CreateNoWindow = true;` messes something up somewhere.
I think that `psi.WindowStyle = ProcessWindowStyle.Hidden;` should work just fine.

The following script works fine from Factor.exe without flashing a console window:
```
<process>
    { "factor.com" "-e=USE: io \"12\" write" } >>command
    t >>hidden
ascii [ input-stream get stream-lines . ] with-process-reader

> { "12" }
```

The `hidden` property triggers this code in io.launcher.windows:
```
        flags{ STARTF_USESTDHANDLES STARTF_USESHOWWINDOW } >>dwFlags
        SW_HIDE >>wShowWindow 
```
So, it's essentially equivalent to the `psi.WindowStyle = ProcessWindowStyle.Hidden` in .NET code as far as I can tell (but I'm not a .NET developer, so I may miss something).

I found some docs that seem to be related to the `CreateNoWindow`, see here: https://docs.microsoft.com/en-us/windows/win32/procthread/process-creation-flags (search for `CREATE_NO_WINDOW`). There is text "the console handle for the application is not set", which makes me question whether the console apps should be able to produce any output at all with that option.

I don't have a way to experiment with .NET apps to confirm whether setting `CreateNoWindow` suppresses output of standard applications (like a batch script with some `echo` calls in it) and whether the behavior is the same for the factor.com script above.

**Comment by erg** [comment] 2020-07-02 17:54
I think we can close this. If there are more issues please reopen.

**Closed by erg** 2020-07-02 17:54 UTC
Labels: command-line, console, io, script, terminal, windows

**Comment by MortezaRahmaniJRP** [comment] 2020-07-03 16:39
Ok
