### ISSUE TITLE
reproducible linux32 gc bug in load-all on git id ad9d0c171b963c7ca4fc1b1f345acbda077c866b

### ISSUE THREAD

**Issue by erg** [factor/factor#1439] opened 2015-08-14 17:38 UTC
```
You have triggered a bug in Factor. Please report.
critical_error: accessors:slot<<: Bad symbol specifier in compute_external_address: afcc0137
Starting low level debugger...
Basic commands:
  q ^D             -- quit Factor
  c                -- continue executing Factor - NOT SAFE
  t                -- throw exception in Factor - NOT SAFE
  .s .r .c         -- print data, retain, call stacks
  help             -- full help, including advanced commands

> ==== DATA STACK:


You have triggered a bug in Factor. Please report.
critical_error: accessors:scale>>: Bad symbol specifier in compute_external_address: afd80137
Starting low level debugger...
Basic commands:
  q ^D             -- quit Factor


Loading resource:basis/checksums/xxhash/xxhash.factor
You have triggered a bug in Factor. Please report.
critical_error: accessors:scale>>: Bad symbol specifier in compute_external_address: afcc0137
Starting low level debugger...
```

**Comment by erg** [comment] 2015-08-14 17:38
Something about accessors causes a gc crash?

**Comment by bjourne** [comment] 2015-08-14 19:56
Is it reproducible?

**Comment by erg** [comment] 2015-08-14 19:57
http://downloads.factorcode.org/images/build/

Seems to be crashing a lot on this particular git id. Try with a load all?

**Comment by erg** [comment] 2015-08-14 19:57
Crashing consistently*

**Comment by erg** [comment] 2015-08-14 20:46
Oh, this is on linux32 btw. Probably won't crash on other platforms.

**Comment by erg** [comment] 2015-08-14 22:22
@bjourne Are you on the factor builds list? I get almost all of my random gc bug reports/ideas from failed builds.

Anyone else who wants to be on the list, lemme know!

**Comment by bjourne** [comment] 2015-08-14 23:22
Yeah, please add me! So to reproduce I checkout ad9d0c171b963c7ca4fc1b1f345acbda077c866b build and run `load-all`?

**Comment by erg** [comment] 2015-08-14 23:32
Yep!

**Comment by bjourne** [comment] 2015-08-18 15:20
I can't get it to crash. But it is probably because I don't have as many 32 bit libraries as your test machine has. It's probably the same bug as in #1223 and #756 and must be something 32 bit specific since it doesn't happen on other platforms...

The "bad symbol specifier" error is very strange. It should only happen if the word has an `RT_DLSYM` relocation, but it should only have that if it is a word that calls a c function.

**Comment by mrjbq7** [comment] 2024-02-14 04:02
Closing this for now, it's been awhile.

**Closed by mrjbq7** 2024-02-14 04:02 UTC
Labels: reloading, crash, gc, linux, stochastic-error, cross-platform-difference, maybe-close-this
