### ISSUE TITLE
DPI scaling for Wayland/X

### ISSUE THREAD

**Issue by bpollack** [factor/factor#2030] opened 2018-08-03 00:15 UTC
Unless I'm missing something, Factor on Linux doesn't support DPI scaling. Looking at how we're doing this in the existing code, I don't think it'll be *too* bad, and it'd make my life easier. (Currently, I'm sticking to my Mac for Factor work, even though I use Linux for everything else.)

**Comment by bpollack** [comment] 2018-08-03 00:32
I tried adding this for Windows last summer (I think?). The all-worlds bit wasn't a huge deal; Windows sends notifications on display switch, and Factor can switch DPI on-the-fly. The tricky thing was non-integer scaling. If I try this again, I may just only do integer multipliers, at least initially, for that reason. The good news is that Ubuntu also only does that by default, so we can probably cover a relatively wide breadth of Linux users pretty easily (whereas e.g. the 72dpi/96dpi factor on Windows is really common).

**Comment by bpollack** [comment] 2018-08-03 00:36
Well, actually [that was two years ago](https://github.com/bpollack/factor/tree/hidpi), right before I entered management, and it looks like handling origin positioning was actually the tricky bit. I can see if this is useful/salvageable.

**Comment by AlexIljin** [comment] 2018-08-03 05:50
In the [commit](https://github.com/bpollack/factor/commit/3eec670d859a2bce3a8eb773420fef5e0373ad96) @bpollack mentioned above, there is `<assemblyIdentity type="win32"` in `factor.exe.manifest`. I suppose that needs to be modified for 64-bit builds.

**Comment by bpollack** [comment] 2018-08-03 08:11
@AlexIljin Nope, it’s fine. Probably worth reading about manifests and HiDPI mode support on Windows 8.1 and higher before trying to use that commit.

**Comment by erg** [comment] 2021-12-18 22:17
Closing as a dupe of https://github.com/factor/factor/issues/1615

If it's not a dupe, reopen with why :)

**Closed by erg** 2021-12-18 22:17 UTC
Labels: ui, linux, retina, x11
