### ISSUE TITLE
macOS console.app reports: AEGetDescData of non-desc type 'reco' not a good idea

### ISSUE THREAD

**Issue by erg** [factor/factor#1986] opened 2018-03-26 06:03 UTC
``10.13.4 Beta (17E190a)``

```
error	19:12:27.157059 -0500	factor	        AEGetDescData of non-desc type 'reco' not a good idea
```

**Comment by hendriks73** [comment] 2019-07-24 08:18
`AE` error messages are typically connected to the Apple Event subsystem. So to find the cause for this, you might want to look for AppleScript code.

**Comment by mrjbq7** [comment] 2023-08-26 01:07
Don't see this on newer macOS, closing.

**Closed by mrjbq7** 2023-08-26 01:07 UTC
Labels: macOS, terminal, exceptions, cocoa
