### ISSUE TITLE
Pango text rendering is garbled

### ISSUE THREAD

**Issue by gifti258** [factor/factor#2485] opened 2021-09-05 01:11 UTC
A few months ago, text in the listener (and other windows) suddenly started to be mostly invisible or cut off for me.

![Bildschirmfoto_2021-09-05_03-06-20](https://user-images.githubusercontent.com/80504430/132111658-af388964-cc3a-4af5-bc9d-8431bc28aa86.png)

**Comment by mrjbq7** [comment] 2021-12-18 23:53
Are you still seeing this problem?

I can't reproduce on any of my linux boxes.

**Comment by gifti258** [comment] 2021-12-20 08:09
Yup, still broken. I use Arch32 on a 32bit machine, maybe that's why? Have you tried it with that distribution?

**Comment by gifti258** [comment] 2021-12-20 15:48
I installed Debian today, because Arch fell apart some more. Here it works flawlessly. So I think it's definitely an issue with Arch32 packaging.

**Comment by erg** [comment] 2021-12-20 18:55
Can we close this as an arch bug?

**Comment by mrjbq7** [comment] 2021-12-20 18:57
Is Debian also 32-bit and working?

Or maybe it’s a bug with our 32-bit pango?

**Comment by gifti258** [comment] 2021-12-20 19:00
It's on the same 32bit machine, so this Debian install is necessarily 32bit, also.

**Comment by erg** [comment] 2021-12-20 19:16
If you want to report this issue to the Arch Linux 32 pango llibrary, go for it.

On our end, it doesn't look like there's anything to do? Closing for now.

**Closed by erg** 2021-12-20 19:16 UTC
Labels: ui, listener, tools, rendering, 32bit, ui-text, pango, arch-linux
