### ISSUE TITLE
Mutable Locals :> ( ...! ) Behavior Needs Clarification

### ISSUE THREAD

**Issue by alex-ilin** [factor/factor#2089] opened 2018-12-27 00:50 UTC
Here's the simplified version of the code that allowed me to waste hours of debugging time:
```
:: locals-test ( fail? -- a b c )
    0 :> a! 0 :> b! 0 :> c!
    fail? [
        1 2 3 :> ( a! b! c! )
    ] [
        1 a! 2 b! 3 c!
    ] if a b c ;

{ 1 2 3 } [ f locals-test ] unit-test
{ 1 2 3 } [ t locals-test ] unit-test
```
The documentation is not clear on whether the `:>` word always defines new locals, or can be used to assign values to existing locals. I expected that since the locals defined in the outer scope are mutable, and since I use the exclamation point inside the `:> ( ...! )`, I will make an assignment to the existing mutable locals, but apparently this is not the case.

Do you think it could be implemented in a way that both unit-tests no longer fail?
Or do you think we could add a new parsing word, like `:>!` for this use case?
I encountered this issue while porting some code from a language that allows multiple return values from a function (Julia).

**Comment by erg** [comment] 2018-12-27 01:53
I think the ``fail?`` branch assigns new a,b,c that shadow the original? Sadly, this is working as intended I believe.

The difference is binding vs reassignment. Binding forms are ``:>`` and ``:> ( ... )`` which create fresh variables. Reassignment is ``a!`` or ``b!``. So you bind a,b,c and then create a fresh a,b,c in the true branch, which goes out of scope, and the false branch reassigns a,b,c so it works.

I honestly am not the biggest fan of lexical scope because of the shadowing as your example demonstrates, but there it is...most everyone else seems ok with it. What would you want to do to fix it?

I kind of like javascript's ``var`` which is word-scoped, but lots of people seem to hate it. In particular, the use case that always gets me is assigning to variables in both branches of an ``if``, and how you have to pre-declare uninitialized variables and then bind them in both branches (Swift has a compiler pass to check for unbound variables in branches). Having Javascript's ``var`` and ``let`` gives you the best of both worlds, although I believe if you forget to declare either then it defaults to ``var``...

We could print a warning on lexical shadowing but warnings kind of suck, too. My tentative longterm plan is to namespace lexical variables with a sigil, like ``1 _a! 2 _b` and access them like ``a_!`` and ``b_``.  Or some other token besides ``_``

**Comment by AlexIljin** [comment] 2018-12-27 02:14
I like the idea of adding `:>! ( ... )`, which would modify existing variables, as the exclamation point suggests. This would fill the gap in the implementation, and have consistent syntax. As it is, we have multiple ways of binding multiple new variables (`:> ( ... )` and `[| ... |`), but no way to reassign multiple variables.

**Comment by melted** [comment] 2018-12-27 02:39
But `1 2 3 a! b! c!` already works, so what would the win be?

> although I believe if you forget to declare either then it defaults to var...
It's not that sane, it defaults to creating a global.

**Comment by AlexIljin** [comment] 2018-12-27 03:38
The win would be the following. Compare the two calls.
```
: some-word-with-multiple-outputs ( ... inputs -- a b c d e f )
... ;

:: here-we-use-that-word ( -- )
... f f f f f f :> ( a! b! c! d! e! f! ) ! declare the variables
  some-condition [
    some inputs some-word-with-multiple-outputs
    :>! ( a! b! c! d! e! f! )
  ] [
    some other-inputs some-word-with-multiple-outputs
    f! e! d! c! b! a!
  ] if
  ! use the variables...
... ;
```
The `true` branch is much more readable, that's the win.

**Comment by erg** [comment] 2018-12-31 18:11
Thought about it some more, simplest thing would be word-scope, binding/setting in parentheses, and using without parentheses:

```factor
1 ( $a )
$a $a + .
2

1 2 3 ( $a $b $c )
$a $b $c + + .
6

1 2 3 ( $a! $b! $c! )
$a! $b! $c! + + .
6

1 2 3 ( $a! $b! $c! )
4 5 6 ( $a! $b! $c! )
$a! $b! $c! + + .
15

! Errors
1 2 3 ( $a $b $c )
4 5 6 ( $a $b $c ) ! error, immutable variables

1 2 3 ( $a $b $c )
1 2 3 ( $a! $b! $c! ) ! error, shadowing

1 2 3 ( $a! $b! $c! )
1 2 3 ( $a $b $c ) ! error, shadowing
```

**Comment by AlexIljin** [comment] 2019-01-01 02:11
So, the dollar sign would mean parameter binding, and not the `::` word?
In general, I like the `:>` word. Simple parenthesising looks a bit like overkill for the general case of assigning a single variable, and its meaning is less self-evident to read.

I like the shadowing errors in your suggestion.

Typing `( $a! )` instead of `a!`, or even `:> a!` looks a bit much, but syntax is hard, and I think you have a better overview of what makes a consistent and slick experience in the new Factor implementation.

Not sure I like the dollars in the source. On the one hand, it opens a namespace for variables (except we have a lot of formatting words in the help system that sit on that convention already), on the other hand it's extra noise for the source reader. Is the distinction worth introducing? I don't know, but it didn't seem necessary or even conventionally useful up to this point.

**Comment by erg** [comment] 2019-01-01 20:37
The ``::`` word would go away and locals would be allowed everywhere. Obviously we want to fix the walker before inflicting the current locals expansion on everyone, and better still, words that don't use locals don't look any different. I have an almost-working branch where this is changed except I'm running into stack-checker bugs like #2096.

I think reading source without tools is hard enough already without changing what a token does based on where it is in the source file or having to wonder if every token is a word or a variable. The ``$`` fixes that. ``:>`` has no tie-in to the new syntax forms at all -- it's just a throwaway token imo. If all of this ends up looking bad we can just keep the current way or find an even better syntax fit.

**Comment by AlexIljin** [comment] 2019-01-01 23:58
"The `::` word would go away and locals would be allowed everywhere."
So, basically you are saying that from a library feature this gets promoted to the core language? So much for keeping the language minimal?

**Comment by razetime** [comment] 2022-11-12 15:00
Clarification done in 004d2ed, after some discussion with the issue author.

**Closed by razetime** 2022-11-12 15:00 UTC
Labels: locals, correctness, name-clash, shadowing, variable-binding
