### ISSUE TITLE
http://paste.factorcode.org gives links to http://paste.factorcode.org:8080

### ISSUE THREAD

**Issue by jonenst** [factor/factor#1992] opened 2018-04-24 12:11 UTC
It should use http://docs.factorcode.org/content/article-http.server.remapping.html instead to give links without the port.

there's the same problem on http://docs.factorcode.org/search?search=port%20remapping

**Comment by erg** [comment] 2018-06-23 18:42
Duplicate of #692

**Closed by erg** 2018-06-23 18:42 UTC
Labels: factorcode.org, web, website
