### ISSUE TITLE
divisors and factors words in math.primes.factors vocabulary take abnormally long for input of 12345678910111213141516

### ISSUE THREAD

**Issue by chunes3** [factor/factor#2401] opened 2020-12-21 21:21 UTC
The following code should demonstrate the problem:

    ...
    [ 1234567891011121314 divisors drop ] time  -> 3ms
    [ 123456789101112131415 divisors drop ] time -> 4ms
    [ 12345678910111213141516 divisors drop ] time -> 45 minutes (and waiting)
    [ 1234567891011121314151617 divisors drop ] time -> 2ms
    [ 123456789101112131415161718 divisors drop ] time -> 9ms
    ...

Another problem number is `12938291482971275356`. It took about 2 seconds to find its divisors, while the surrounding numbers take a few milliseconds.

Some more problem inputs I found:

    [ 1203650694090333124 factors drop ] time  -> 8.3 seconds
    [ 1203650694090333128 factors drop ] time  -> 18.9 seconds
    [ 62036506940903331216 factors drop ] time  -> 261 milliseconds

The problem is happening in the `(group-factors)` word, which is doing prime factorization. Specifically, this is the loop that takes abnormally long to complete:

`[ 2dup sq < ] [ write-factor next-prime ] until`

@samueltardieu do you have any insights about what might be causing this?

**Comment by samueltardieu** [comment] 2020-12-26 14:15
The algorithm to determine if a number is prime is based on an heuristic one when the number is very large, and thus executes in a very short time.

However, finding the factors of a very large number can take a long time if those factors are themselves very large, since we must attempt division by to prime number smaller than those factors because we cannot guess them. We can attempt to parallelize the process but it would only divide the execution time by the number of hardware threads at best.

Maybe someone knows a better algorithm to factor large numbers, but we are unlikely to find a very efficient non-quantum-computing algorithm.

**Comment by hiljusti** [comment] 2021-02-03 05:07
For what it's worth, running `factor` on my machine gets these problem numbers relatively fast. (milliseconds at most, on a modest laptop)

No, not this Factor, but the `factor` from GNU coreutils: https://github.com/coreutils/coreutils/blob/master/src/factor.c

The code & algorithms used there are... non-trivial to say the least. I see some bit hacking but also some mentions of specific algorithms ("Lucas" and "Miller-Rabin")

**Comment by erg** [comment] 2021-12-18 22:49
We have Lucas-Lehmer and Miller-Rabin primality testing. These finish instantaneously on the test cases. The ``divisors`` word could use one of these and not test if it returns ``f``.

```
12345678910111213141516 lucas-lehmer .
f

12345678910111213141516 miller-rabin .
f
```

**Comment by erg** [comment] 2021-12-19 15:53
https://en.wikipedia.org/wiki/Pollard%27s_rho_algorithm

**Comment by erg** [comment] 2021-12-29 08:00
@chunes3 I ported the Pollard-Rho-Brent algorithm. Check it out!

**Comment by erg** [comment] 2021-12-29 17:02
More algorithms to implement maybe

https://en.wikipedia.org/wiki/Primality_test

- [ ] https://en.wikipedia.org/wiki/Baillie%E2%80%93PSW_primality_test
- [ ] https://en.wikipedia.org/wiki/Pocklington_primality_test

**Comment by erg** [comment] 2021-12-29 19:49
There's potentially a speed regression from `group-factors` to the new `factors` word.

```factor
gc [ 1 10,000,000 [a,b] [ dup group-factors ] { } map>assoc ] time
gc [ 1 10,000,000 [a,b] [ dup factors ] { } map>assoc ] time
```

**Comment by mrjbq7** [comment] 2022-01-15 04:25
Not much of one, and the new algorithm is better for some pathological cases.  Closing this bug.  If anyone wants to implement new algorithms in https://github.com/factor/factor/issues/2401#issuecomment-1002690338 that would be awesome.

**Closed by mrjbq7** 2022-01-15 04:25 UTC
Labels: library, maths, random, algorithms, optimization, primes, number-theory, help-wanted, too-slow
